### ISSUE TITLE
Fork?

### ISSUE THREAD

**Issue by TrickJoker312** [Skoolgq/SkoolTV#2]
Hey! I wanted to know if i am allowed to fork this repository to create another link for the site? I'd appreciate a reply!

**Comment by fowntain** [comment]
> Hey! I wanted to know if i am allowed to fork this repository to create another link for the site? I'd appreciate a reply!

of course! forks are an inherent part of github, so feel free!

**Comment by TrickJoker312** [comment]
Thank you! I'll be sure to credit your work.
